{% set name = "jax-dataclasses" %}
{% set version = "1.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jax_dataclasses-{{ version }}.tar.gz
  sha256: 2e981517271e9405a13dcb475d73ff60ecd5355be7b3e7b4155612cf168db967

build:
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps --no-build-isolation . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - jax
    - jaxlib
    - typing-extensions

test:
  imports:
    - jax_dataclasses
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/brentyi/jax_dataclasses
  summary: Dataclasses + JAX
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - traversaro
